
import { Category, User, Idea, Notification, Organisation, OrganisationType, TechCategory } from './types';

export const CATEGORIES: Category[] = [
  'Governance & Standards',
  'Sovereign Infrastructure',
  'Capital & Risk',
  'Market Design',
  'Talent & Education',
  'Narrative & Influence',
  'Frontier / Radical'
];

export const ORGANISATION_TYPES: OrganisationType[] = [
  'Government & Intergovernmental Agencies',
  'Think Tanks & Policy Institutes',
  'Academic & Research Institutions',
  'Industry & Consulting Reports',
  'Tech Firm',
  'Manufacturer'
];

export const TECH_CATEGORIES: TechCategory[] = [
  'Cloud',
  'Productivity',
  'AI/ML',
  'Security',
  'Chips',
  'Quantum',
  'Satellite'
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    title: 'Proposal Endorsed',
    message: 'Dr. Sarah Chen endorsed your "National AI Incident Database" proposal.',
    timestamp: Date.now() - 1000 * 60 * 15,
    isRead: false,
    type: 'vote'
  },
  {
    id: 'n2',
    title: 'New Working Group',
    message: 'A new working group has been formed for Sovereign AI Stack Blueprint.',
    timestamp: Date.now() - 1000 * 60 * 60 * 2,
    isRead: false,
    type: 'system'
  },
  {
    id: 'n3',
    title: 'Event Reminder',
    message: 'Sovereign AI Infrastructure Summit starts in 24 hours.',
    timestamp: Date.now() - 1000 * 60 * 60 * 5,
    isRead: true,
    type: 'event'
  },
  {
    id: 'n4',
    title: 'New Review',
    message: 'James Wilson left a review on your latest technical spec.',
    timestamp: Date.now() - 1000 * 60 * 60 * 24,
    isRead: true,
    type: 'comment'
  }
];

export const MOCK_USERS: User[] = [
  { 
    id: 'u_admin_p', 
    name: 'Francesca Tabor', 
    password: 'Brazil89*', 
    role: 'Policymaker', 
    organization: 'Global Sovereign Hub', 
    avatar: 'https://picsum.photos/seed/politics/40', 
    points: 10000,
    isAdmin: true
  },
  { 
    id: 'u_admin', 
    name: 'Francesca Tabor', 
    password: 'Brazil89*', 
    role: 'Corporate', 
    organization: 'Sovereign Hub Lead', 
    avatar: 'https://picsum.photos/seed/francesca/40', 
    points: 5000 
  },
  { id: 'u1', name: 'Dr. Sarah Chen', role: 'Academic', organization: 'Stanford AI Policy Lab', avatar: 'https://picsum.photos/seed/sarah/40', points: 1250 },
  { id: 'u2', name: 'James Wilson', role: 'Regulator', organization: 'European Tech Agency', avatar: 'https://picsum.photos/seed/james/40', points: 840 },
  { id: 'u3', name: 'Elena Rodriguez', role: 'Investor', organization: 'Sovereign Capital Partners', avatar: 'https://picsum.photos/seed/elena/40', points: 2100 },
  { id: 'u4', name: 'Marcus Thorne', role: 'Policymaker', organization: 'Ministry of Digital Affairs', avatar: 'https://picsum.photos/seed/marcus/40', points: 560 }
];

export const MOCK_ORGANISATIONS: Organisation[] = [
  // Government & Intergovernmental Agencies
  {
    id: 'org-gov-1',
    name: 'European Commission – DG Connect',
    type: 'Government & Intergovernmental Agencies',
    techCategories: ['Cloud', 'AI/ML', 'Security'],
    description: 'EU publisher of reports on “digital sovereignty”, cloud infrastructure, AI, and critical technology supply chains.',
    location: 'EU',
    avatar: 'https://picsum.photos/seed/dgconnect/100',
    memberCount: 5000,
    verified: true,
    website: 'https://ec.europa.eu/digital-europe',
    delegates: [
      { id: 'd1', name: 'Thierry Breton', role: 'Commissioner for Internal Market', avatar: 'https://picsum.photos/seed/breton/40', quote: 'Digital sovereignty is a prerequisite for our security and our economic prosperity in the 21st century.' }
    ]
  },
  {
    id: 'org-gov-2',
    name: 'French Ministry of Armed Forces / ANSSI',
    type: 'Government & Intergovernmental Agencies',
    techCategories: ['Security', 'Cloud'],
    description: 'French cybersecurity agency; publishes national tech strategy and sovereignty reports.',
    location: 'France',
    avatar: 'https://picsum.photos/seed/anssi/100',
    memberCount: 1200,
    verified: true,
    website: 'https://www.ssi.gouv.fr',
    delegates: [
      { id: 'd2', name: 'Guillaume Poupard', role: 'Director General', avatar: 'https://picsum.photos/seed/poupard/40', quote: 'France must remain at the forefront of cyber defense to protect its strategic interests and democratic values.' }
    ]
  },
  {
    id: 'org-gov-3',
    name: 'German BMWK',
    type: 'Government & Intergovernmental Agencies',
    techCategories: ['AI/ML', 'Chips', 'Productivity'],
    description: 'German Federal Ministry for Economic Affairs and Climate Action. Focus on industrial policy and supply chain security.',
    location: 'Germany',
    avatar: 'https://picsum.photos/seed/bmwk/100',
    memberCount: 3500,
    verified: true,
    website: 'https://www.bmwk.de',
    delegates: [
      { id: 'd3', name: 'Robert Habeck', role: 'Federal Minister', avatar: 'https://picsum.photos/seed/habeck/40', quote: 'Securing our industrial base requires resilient supply chains and a strong domestic semiconductor industry.' }
    ]
  },
  {
    id: 'org-gov-4',
    name: 'National Security Council / OSTP',
    type: 'Government & Intergovernmental Agencies',
    techCategories: ['AI/ML', 'Chips', 'Quantum', 'Security'],
    description: 'USA agency focusing on AI, semiconductors, critical infrastructure, and national tech sovereignty.',
    location: 'USA',
    avatar: 'https://picsum.photos/seed/nscostp/100',
    memberCount: 800,
    verified: true,
    website: 'https://www.whitehouse.gov/ostp',
    delegates: [
      { id: 'd4', name: 'Arati Prabhakar', role: 'Director of OSTP', avatar: 'https://picsum.photos/seed/arati/40', quote: 'Innovation is the bedrock of our national security; we must lead in the technologies of the future.' }
    ]
  },
  {
    id: 'org-tt-1',
    name: 'Bruegel',
    type: 'Think Tanks & Policy Institutes',
    techCategories: ['Productivity', 'AI/ML'],
    description: 'European think tank on digital economy, industrial policy, and tech sovereignty.',
    location: 'EU',
    avatar: 'https://picsum.photos/seed/bruegel/100',
    memberCount: 80,
    verified: true,
    website: 'https://www.bruegel.org',
    delegates: [
      { id: 'd5', name: 'Maria Demertzis', role: 'Deputy Director', avatar: 'https://picsum.photos/seed/maria/40', quote: 'The digital transition must be governed by rules that ensure fair competition and respect European values.' }
    ]
  },
  {
    id: 'org-acad-1',
    name: 'Stanford Cyber Policy Center',
    type: 'Academic & Research Institutions',
    techCategories: ['AI/ML', 'Security'],
    description: 'Leading research on AI, data, and digital sovereignty.',
    location: 'USA',
    avatar: 'https://picsum.photos/seed/stanford/100',
    memberCount: 150,
    verified: true,
    website: 'https://cyber.fsi.stanford.edu',
    delegates: [
      { id: 'd6', name: 'Nate Persily', role: 'Co-Director', avatar: 'https://picsum.photos/seed/nate/40', quote: 'The intersection of technology and democracy is the defining challenge of our time.' }
    ]
  },
  {
    id: 'org-ind-1',
    name: 'McKinsey & Company',
    type: 'Industry & Consulting Reports',
    techCategories: ['AI/ML', 'Chips', 'Productivity'],
    description: 'Global strategy reports on tech sovereignty, AI strategy, and semiconductor supply chains.',
    location: 'Global',
    avatar: 'https://picsum.photos/seed/mckinsey/100',
    memberCount: 30000,
    verified: true,
    website: 'https://www.mckinsey.com',
    delegates: [
      { id: 'd7', name: 'Bob Sternfels', role: 'Global Managing Partner', avatar: 'https://picsum.photos/seed/bob/40', quote: 'Accelerating digital transformation is essential for global growth and resilience.' }
    ]
  }
];

export const EVENTS = [
  {
    id: 'e1',
    title: 'Sovereign AI Infrastructure Summit',
    description: 'A high-level convening of technical architects and policy leaders to define the requirements for regional compute autonomy and secure model residency.',
    date: 'Oct 24, 2026',
    time: '14:00 - 17:00 UTC',
    location: 'Virtual Hall',
    type: 'Board Review',
    attendees: 42,
    status: 'Upcoming',
    agenda: [
      { time: '14:00', label: 'Opening Plenary', meta: 'Strategic Vision for Sovereign Compute' },
      { time: '15:00', label: 'Technical Review', meta: 'Genesis Node Performance Benchmarks' },
      { time: '16:30', label: 'Ratification', meta: 'Voting on Data Residency Standards' }
    ],
    objectives: [
      { title: 'Define Standards', desc: 'Reach consensus on the minimal hardware specs for Genesis Nodes.', icon: 'ShieldCheck' },
      { title: 'Capital Alignment', desc: 'Secure initial funding commitments for Phase 1 rollout.', icon: 'Award' }
    ]
  },
  {
    id: 'e2',
    title: 'Capital Nexus: Alignment Lab',
    description: 'Working session focused on reconciling Sovereign Wealth Fund mandates with the long-term horizons of strategic technology investments.',
    date: 'Oct 28, 2026',
    time: '10:00 - 12:00 UTC',
    location: 'London / Hybrid',
    type: 'Investor Lab',
    attendees: 15,
    status: 'Planned',
    agenda: [
      { time: '10:00', label: 'Portfolio Mapping', meta: 'Analyzing current dependency exposure' },
      { time: '11:00', label: 'Horizon Scanning', meta: 'Long-term value of tech independence' }
    ],
    objectives: [
      { title: 'Risk Mapping', desc: 'Identify critical dependencies on external semiconductor supply chains.', icon: 'Info' }
    ]
  },
  {
    id: 'e3',
    title: 'Diplomatic Feedback: G7 Protocol',
    description: 'Adversarial simulation analyzing the friction points of proposed G7-aligned Internet fragmentation and data localization protocols.',
    date: 'Nov 02, 2026',
    time: '16:00 - 18:00 UTC',
    location: 'Closed Session',
    type: 'Adversarial Review',
    attendees: 8,
    status: 'Upcoming',
    agenda: [
      { time: '16:00', label: 'Shock Scenario', meta: 'Simulating a total DNS embargo' },
      { time: '17:00', label: 'Response Strategy', meta: 'Drafting the diplomatic counter-proposal' }
    ],
    objectives: [
      { title: 'Neutralize Friction', desc: 'Identify talking points to minimize G7 regulatory pushback.', icon: 'Globe' }
    ]
  }
];

export const INITIAL_IDEAS: Idea[] = [
  {
    id: "idea-005",
    title: "AI Model Passport System",
    description: "A standardized identity and registry for deployed AI models, containing metadata such as training data class, ownership, risk profile, update history, and deployment context. Enables traceability, accountability, and cross-border interoperability.",
    category: "Governance & Standards",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T10:30:00Z").getTime(),
    status: "Proposed",
    impactScore: 95,
    feasibilityScore: 79,
    revenueScore: 60,
    sovereigntyScore: 96,
    votes: { up: 0, down: 0 },
    comments: [],
    tags: ["model-registry", "traceability", "accountability", "standards"],
    version: 1
  },
  {
    id: "idea-004",
    title: "National AI Incident Database",
    description: "A centralized, mandatory reporting database for AI-related failures, harms, and near-misses, modeled after aviation accident databases. Enables shared learning, trend analysis, and evidence-based governance.",
    category: "Governance & Standards",
    authorId: "u3",
    authorName: "Elena Rodriguez",
    timestamp: new Date("2026-02-04T10:20:00Z").getTime(),
    status: "Proposed",
    impactScore: 90,
    feasibilityScore: 65,
    revenueScore: 32,
    sovereigntyScore: 94,
    votes: { up: 0, down: 0 },
    comments: [],
    tags: ["incident-reporting", "transparency", "public-infrastructure"],
    version: 1
  },
  {
    id: "idea-003",
    title: "Algorithmic Audit-as-a-Service",
    description: "A continuous auditing platform for AI systems offering real-time compliance monitoring, automated alerts, incident reporting pipelines, and regulator-facing dashboards. Moves audits from periodic reviews to ongoing assurance.",
    category: "Governance & Standards",
    authorId: "u2",
    authorName: "James Wilson",
    timestamp: new Date("2026-02-04T10:12:00Z").getTime(),
    status: "Proposed",
    impactScore: 84,
    feasibilityScore: 86,
    revenueScore: 91,
    sovereigntyScore: 69,
    votes: { up: 0, down: 0 },
    comments: [],
    tags: ["auditing", "compliance", "saas", "monitoring"],
    version: 1
  },
  {
    id: "idea-002",
    title: "AI Risk Rating Agency",
    description: "An independent organization that rates AI systems using standardized risk metrics, issuing grades (e.g., AAA to Junk) similar to credit rating agencies. Ratings inform investors, insurers, regulators, and customers without imposing direct regulatory mandates.",
    category: "Governance & Standards",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T10:05:00Z").getTime(),
    status: "Proposed",
    impactScore: 87,
    feasibilityScore: 74,
    revenueScore: 72,
    sovereigntyScore: 78,
    votes: { up: 0, down: 0 },
    comments: [],
    tags: ["risk-rating", "market-discipline", "certification", "trust"],
    version: 1
  },
  {
    id: "idea-001",
    title: "AI Stress Testing Regime",
    description: "A mandatory stress-testing framework for AI systems, analogous to bank stress tests. Systems are evaluated against predefined adverse scenarios including bias shocks, data poisoning, model collapse, regulatory changes, and adversarial attacks. Results are reported to regulators and system owners to assess systemic and localized risk.",
    category: "Governance & Standards",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T10:00:00Z").getTime(),
    status: "Proposed",
    impactScore: 92,
    feasibilityScore: 68,
    revenueScore: 55,
    sovereigntyScore: 89,
    votes: { up: 0, down: 0 },
    comments: [],
    tags: ["stress-testing", "systemic-risk", "ai-safety", "regulation"],
    version: 1
  },
  {
    id: "idea-010",
    title: "Compute Sovereignty Index",
    description: "A public ranking of countries based on their level of compute independence, including chip supply chains, data center capacity, cloud reliance, and AI infrastructure control. Designed to influence policy, investment, and public discourse.",
    category: "Sovereign Infrastructure",
    authorId: "u4",
    authorName: "Marcus Thorne",
    timestamp: new Date("2026-02-04T11:30:00Z").getTime(),
    status: "Proposed",
    impactScore: 88,
    feasibilityScore: 85,
    revenueScore: 46,
    sovereigntyScore: 91,
    votes: { up: 18, down: 2 },
    comments: [],
    tags: ["compute-sovereignty", "index", "policy-influence", "metrics"],
    version: 1
  },
  {
    id: "idea-009",
    title: "European and Middle East Trusted Cloud Alliance",
    description: "A federated alliance of European and Middle Eastern cloud providers offering a trusted alternative to hyperscalers. Operates under shared standards for data residency, security, compliance, and interoperability while remaining regionally governed.",
    category: "Sovereign Infrastructure",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T11:22:00Z").getTime(),
    status: "Proposed",
    impactScore: 93,
    feasibilityScore: 64,
    revenueScore: 75,
    sovereigntyScore: 97,
    votes: { up: 31, down: 4 },
    comments: [],
    tags: ["trusted-cloud", "federated-infrastructure", "regional-alliance", "strategic-autonomy"],
    version: 1
  },
  {
    id: "idea-008",
    title: "Critical Infrastructure Air-Gap AI",
    description: "Offline-capable AI systems designed for critical infrastructure environments such as defense, energy, water, and transport. Systems operate without cloud connectivity, prioritizing security, resilience, and operational continuity.",
    category: "Sovereign Infrastructure",
    authorId: "u3",
    authorName: "Elena Rodriguez",
    timestamp: new Date("2026-02-04T11:15:00Z").getTime(),
    status: "Proposed",
    impactScore: 86,
    feasibilityScore: 82,
    revenueScore: 89,
    sovereigntyScore: 92,
    votes: { up: 56, down: 3 },
    comments: [],
    tags: ["air-gapped-ai", "critical-infrastructure", "offline-systems", "security"],
    version: 1
  },
  {
    id: "idea-007",
    title: "Regional Data Trusts",
    description: "Public-interest data cooperatives where citizens and companies pool data under trustee governance. Data is licensed for AI development under transparent rules, enabling innovation while preventing monopolistic control by large platforms.",
    category: "Sovereign Infrastructure",
    authorId: "u2",
    authorName: "James Wilson",
    timestamp: new Date("2026-02-04T11:08:00Z").getTime(),
    status: "Proposed",
    impactScore: 91,
    feasibilityScore: 69,
    revenueScore: 50,
    sovereigntyScore: 95,
    votes: { up: 44, down: 8 },
    comments: [],
    tags: ["data-trusts", "data-sovereignty", "cooperatives", "public-interest"],
    version: 1
  },
  {
    id: "idea-006",
    title: "Sovereign AI Stack Blueprint",
    description: "An open reference architecture for national or regional AI systems covering cloud infrastructure, data layers, compute/chips, and a governance layer. Designed as an exportable blueprint enabling governments to deploy sovereign AI capabilities rapidly.",
    category: "Sovereign Infrastructure",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T11:00:00Z").getTime(),
    status: "Proposed",
    impactScore: 94,
    feasibilityScore: 76,
    revenueScore: 68,
    sovereigntyScore: 98,
    votes: { up: 72, down: 5 },
    comments: [],
    tags: ["sovereign-stack", "reference-architecture", "national-ai", "export-model"],
    version: 1
  },
  {
    id: "idea-015",
    title: "Algorithmic Liability Pool",
    description: "A mutual insurance structure where AI developers and deployers contribute to a shared liability pool covering algorithmic harms. Risk-adjusted contributions incentivize safer system design while spreading catastrophic risk.",
    category: "Capital & Risk",
    authorId: "u2",
    authorName: "James Wilson",
    timestamp: new Date("2026-02-04T12:30:00Z").getTime(),
    status: "Proposed",
    impactScore: 88,
    feasibilityScore: 72,
    revenueScore: 70,
    sovereigntyScore: 81,
    votes: { up: 14, down: 2 },
    comments: [],
    tags: ["mutual-insurance", "liability", "risk-pooling", "collective-action"],
    version: 1
  },
  {
    id: "idea-014",
    title: "AI Escrow and Bonding System",
    description: "A mechanism requiring firms to post financial bonds or escrow funds against potential AI-related harms, similar to environmental or construction bonds. Funds are released or forfeited based on compliance, incident history, and remediation.",
    category: "Capital & Risk",
    authorId: "u4",
    authorName: "Marcus Thorne",
    timestamp: new Date("2026-02-04T12:22:00Z").getTime(),
    status: "Proposed",
    impactScore: 91,
    feasibilityScore: 66,
    revenueScore: 69,
    sovereigntyScore: 87,
    votes: { up: 32, down: 8 },
    comments: [],
    tags: ["bonding", "escrow", "liability", "incentive-alignment"],
    version: 1
  },
  {
    id: "idea-013",
    title: "Sovereign Venture Fund Advisory",
    description: "Advisory services focused on designing governance, risk controls, and investment frameworks for state-backed and sovereign venture funds investing in AI and strategic technologies, with emphasis on transparency and long-term national interest.",
    category: "Capital & Risk",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T12:15:00Z").getTime(),
    status: "Proposed",
    impactScore: 85,
    feasibilityScore: 83,
    revenueScore: 88,
    sovereigntyScore: 89,
    votes: { up: 45, down: 1 },
    comments: [],
    tags: ["sovereign-funds", "venture-capital", "governance", "state-investment"],
    version: 1
  },
  {
    id: "idea-012",
    title: "Regulatory Capital Relief Models for AI Governance",
    description: "Frameworks and quantitative models that allow banks and financial institutions to reduce regulatory capital charges by demonstrating strong AI governance, controls, and risk mitigation, analogous to operational risk or model risk relief.",
    category: "Capital & Risk",
    authorId: "u3",
    authorName: "Elena Rodriguez",
    timestamp: new Date("2026-02-04T12:08:00Z").getTime(),
    status: "Proposed",
    impactScore: 90,
    feasibilityScore: 71,
    revenueScore: 87,
    sovereigntyScore: 75,
    votes: { up: 21, down: 3 },
    comments: [],
    tags: ["banking", "capital-relief", "regulatory-models", "ai-governance"],
    version: 1
  },
  {
    id: "idea-011",
    title: "AI Risk Insurance Brokerage",
    description: "A specialist insurance brokerage focused on AI-related risks. The brokerage helps firms assess, document, and mitigate AI risks in order to qualify for coverage, negotiate premiums, and design appropriate policy structures.",
    category: "Capital & Risk",
    authorId: "u2",
    authorName: "James Wilson",
    timestamp: new Date("2026-02-04T12:00:00Z").getTime(),
    status: "Proposed",
    impactScore: 82,
    feasibilityScore: 89,
    revenueScore: 93,
    sovereigntyScore: 64,
    votes: { up: 18, down: 1 },
    comments: [],
    tags: ["insurance", "risk-brokerage", "ai-liability", "advisory"],
    version: 1
  },
  {
    id: "idea-020",
    title: "AI Model Interoperability Protocols",
    description: "Open technical and governance standards that allow AI models to be switched, migrated, or composed across providers. Reduces vendor lock-in and promotes competitive, resilient AI ecosystems.",
    category: "Market Design",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T13:30:00Z").getTime(),
    status: "Proposed",
    impactScore: 92,
    feasibilityScore: 68,
    revenueScore: 59,
    sovereigntyScore: 91,
    votes: { up: 18, down: 4 },
    comments: [],
    tags: ["interoperability", "open-standards", "vendor-lock-in", "portability"],
    version: 1
  },
  {
    id: "idea-019",
    title: "Regulatory Sandbox Platform for AI",
    description: "A digital platform enabling companies to test AI systems under regulator supervision. Provides tooling for controlled experimentation, reporting, and compliance feedback, accelerating innovation while managing risk.",
    category: "Market Design",
    authorId: "u4",
    authorName: "Marcus Thorne",
    timestamp: new Date("2026-02-04T13:22:00Z").getTime(),
    status: "Proposed",
    impactScore: 89,
    feasibilityScore: 79,
    revenueScore: 74,
    sovereigntyScore: 88,
    votes: { up: 22, down: 1 },
    comments: [],
    tags: ["regulatory-sandbox", "policy-testing", "compliance", "experimentation"],
    version: 1
  },
  {
    id: "idea-018",
    title: "Trusted Dataset Marketplace",
    description: "A curated marketplace offering legally clean, well-documented datasets for AI training and validation. Datasets include provenance, licensing terms, and compliance guarantees, serving regulated AI developers and public-sector users.",
    category: "Market Design",
    authorId: "u3",
    authorName: "Elena Rodriguez",
    timestamp: new Date("2026-02-04T13:15:00Z").getTime(),
    status: "Proposed",
    impactScore: 87,
    feasibilityScore: 88,
    revenueScore: 90,
    sovereigntyScore: 76,
    votes: { up: 45, down: 2 },
    comments: [],
    tags: ["datasets", "marketplace", "data-compliance", "ai-training"],
    version: 1
  },
  {
    id: "idea-017",
    title: "AI Procurement Certification Scheme",
    description: "A certification program that designates AI vendors as approved suppliers based on governance, security, and compliance criteria. Certifications are used in public and private procurement processes to simplify vendor selection and enforce standards.",
    category: "Market Design",
    authorId: "u2",
    authorName: "James Wilson",
    timestamp: new Date("2026-02-04T13:08:00Z").getTime(),
    status: "Proposed",
    impactScore: 90,
    feasibilityScore: 84,
    revenueScore: 86,
    sovereigntyScore: 85,
    votes: { up: 31, down: 3 },
    comments: [],
    tags: ["certification", "procurement", "standards-enforcement", "trust"],
    version: 1
  },
  {
    id: "idea-016",
    title: "Open AI Governance Standards Body",
    description: "An independent, multi-stakeholder standards body for AI governance, analogous to the W3C. The organization convenes governments, firms, civil society, and technical experts to define interoperable governance, audit, and accountability standards.",
    category: "Market Design",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T13:00:00Z").getTime(),
    status: "Proposed",
    impactScore: 96,
    feasibilityScore: 67,
    revenueScore: 48,
    sovereigntyScore: 92,
    votes: { up: 64, down: 5 },
    comments: [],
    tags: ["standards", "governance", "institution-building", "agenda-setting"],
    version: 1
  },
  {
    id: "idea-025",
    title: "Regulator-in-Residence Programme",
    description: "A structured program placing regulators inside firms for fixed periods to observe AI development, governance, and deployment practices. Encourages mutual learning, trust-building, and better-informed regulation.",
    category: "Talent & Education",
    authorId: "u4",
    authorName: "Marcus Thorne",
    timestamp: new Date("2026-02-04T14:30:00Z").getTime(),
    status: "Proposed",
    impactScore: 86,
    feasibilityScore: 63,
    revenueScore: 42,
    sovereigntyScore: 90,
    votes: { up: 12, down: 2 },
    comments: [],
    tags: ["regulators", "secondments", "capacity-building", "policy-learning"],
    version: 1
  },
  {
    id: "idea-024",
    title: "Governance Operating System (G-OS)",
    description: "A software platform providing dashboards, workflows, and reporting tools for AI governance. Acts as an operating system layer coordinating oversight, audits, risk management, and regulatory engagement across an organization.",
    category: "Talent & Education",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T14:22:00Z").getTime(),
    status: "Proposed",
    impactScore: 94,
    feasibilityScore: 78,
    revenueScore: 94,
    sovereigntyScore: 82,
    votes: { up: 45, down: 4 },
    comments: [],
    tags: ["governance-os", "platform", "dashboards", "oversight"],
    version: 1
  },
  {
    id: "idea-023",
    title: "Shadow AI Detection Tools",
    description: "Software tools that detect and monitor unofficial or unauthorized AI usage inside organizations. Identifies compliance gaps, data leakage risks, and unmanaged model deployments in real time.",
    category: "Talent & Education",
    authorId: "u3",
    authorName: "Elena Rodriguez",
    timestamp: new Date("2026-02-04T14:15:00Z").getTime(),
    status: "Proposed",
    impactScore: 89,
    feasibilityScore: 87,
    revenueScore: 92,
    sovereigntyScore: 73,
    votes: { up: 29, down: 3 },
    comments: [],
    tags: ["shadow-ai", "compliance", "risk-detection", "internal-controls"],
    version: 1
  },
  {
    id: "idea-022",
    title: "AI Board Simulation Labs",
    description: "Executive training labs that simulate AI-related crises through role-play and scenario exercises. Boards and senior leaders practice decision-making under regulatory, reputational, and operational stress.",
    category: "Talent & Education",
    authorId: "u2",
    authorName: "James Wilson",
    timestamp: new Date("2026-02-04T14:08:00Z").getTime(),
    status: "Proposed",
    impactScore: 83,
    feasibilityScore: 90,
    revenueScore: 85,
    sovereigntyScore: 69,
    votes: { up: 18, down: 1 },
    comments: [],
    tags: ["executive-training", "simulation", "board-governance", "crisis-management"],
    version: 1
  },
  {
    id: "idea-021",
    title: "AI Governance Officer Certification",
    description: "A professional certification establishing AI Governance Officer as a recognized role, similar to Chartered Accountant or Certified Risk Manager. Covers governance frameworks, risk management, compliance, and oversight of AI systems.",
    category: "Talent & Education",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T14:00:00Z").getTime(),
    status: "Proposed",
    impactScore: 91,
    feasibilityScore: 82,
    revenueScore: 88,
    sovereigntyScore: 84,
    votes: { up: 37, down: 2 },
    comments: [],
    tags: ["certification", "professional-standards", "governance", "talent"],
    version: 1
  },
  {
    id: "idea-030",
    title: "AI Governance Fellowship",
    description: "A selective fellowship program training emerging leaders in AI governance, policy, and risk management. Combines education, placements, and network-building to create long-term influence and shared norms.",
    category: "Narrative & Influence",
    authorId: "u4",
    authorName: "Marcus Thorne",
    timestamp: new Date("2026-02-04T15:30:00Z").getTime(),
    status: "Proposed",
    impactScore: 91,
    feasibilityScore: 74,
    revenueScore: 49,
    sovereigntyScore: 93,
    votes: { up: 15, down: 0 },
    comments: [],
    tags: ["fellowship", "leadership", "network-effects", "capacity-building"],
    version: 1
  },
  {
    id: "idea-029",
    title: "Strategic AI Foresight Unit",
    description: "A dedicated horizon-scanning and futures analysis unit monitoring emerging AI capabilities, risks, geopolitical shifts, and regulatory trends. Produces briefs, scenarios, and early-warning indicators.",
    category: "Narrative & Influence",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T15:22:00Z").getTime(),
    status: "Proposed",
    impactScore: 87,
    feasibilityScore: 75,
    revenueScore: 58,
    sovereigntyScore: 89,
    votes: { up: 8, down: 1 },
    comments: [],
    tags: ["foresight", "horizon-scanning", "strategy", "early-warning"],
    version: 1
  },
  {
    id: "idea-028",
    title: "AI Failures Library",
    description: "A curated, continuously updated library of documented AI failures, near-misses, and systemic breakdowns. Case studies are anonymized where needed and structures for education, governance learning, and deterrence.",
    category: "Narrative & Influence",
    authorId: "u3",
    authorName: "Elena Rodriguez",
    timestamp: new Date("2026-02-04T15:15:00Z").getTime(),
    status: "Proposed",
    impactScore: 90,
    feasibilityScore: 79,
    revenueScore: 47,
    sovereigntyScore: 91,
    votes: { up: 24, down: 2 },
    comments: [],
    tags: ["failures", "case-studies", "education", "risk-learning"],
    version: 1
  },
  {
    id: "idea-027",
    title: "AI Risk Index",
    description: "A quarterly index tracking systemic and sector-specific AI risks using indicators such as incidents, regulatory actions, and infrastructure exposure. Designed as a recurring signal for markets, media, and policymakers.",
    category: "Narrative & Influence",
    authorId: "u2",
    authorName: "James Wilson",
    timestamp: new Date("2026-02-04T15:08:00Z").getTime(),
    status: "Proposed",
    impactScore: 89,
    feasibilityScore: 86,
    revenueScore: 63,
    sovereigntyScore: 88,
    votes: { up: 12, down: 0 },
    comments: [],
    tags: ["risk-index", "market-signal", "metrics", "media"],
    version: 1
  },
  {
    id: "idea-026",
    title: "Annual AI Sovereignty Report",
    description: "A flagship annual publication analyzing global AI sovereignty trends, risks, infrastructure, and governance. Positioned as a definitive reference for policymakers, investors, and industry leaders, similar in influence to World Economic Forum reports.",
    category: "Narrative & Influence",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T15:00:00Z").getTime(),
    status: "Proposed",
    impactScore: 92,
    feasibilityScore: 88,
    revenueScore: 54,
    sovereigntyScore: 95,
    votes: { up: 42, down: 3 },
    comments: [],
    tags: ["report", "thought-leadership", "ai-sovereignty", "agenda-setting"],
    version: 1
  },
  {
    id: "idea-035",
    title: "Post-Incident AI Truth Commissions",
    description: "Formal, independent commissions convened after major AI failures or disasters to investigate causes, accountability, and systemic lessons. Findings are published to support institutional learning and policy reform.",
    category: "Frontier / Radical",
    authorId: "u4",
    authorName: "Marcus Thorne",
    timestamp: new Date("2026-02-04T16:30:00Z").getTime(),
    status: "Proposed",
    impactScore: 88,
    feasibilityScore: 60,
    revenueScore: 27,
    sovereigntyScore: 91,
    votes: { up: 4, down: 0 },
    comments: [],
    tags: ["truth-commissions", "accountability", "post-incident-review", "institutional-learning"],
    version: 1
  },
  {
    id: "idea-034",
    title: "AI Kill-Switch Governance Protocol",
    description: "Standardized governance and technical protocols enabling the safe, auditable shutdown of AI systems under predefined emergency conditions. Includes authorization chains, safeguards against abuse, and post-activation review.",
    category: "Frontier / Radical",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T16:22:00Z").getTime(),
    status: "Proposed",
    impactScore: 93,
    feasibilityScore: 68,
    revenueScore: 45,
    sovereigntyScore: 94,
    votes: { up: 12, down: 1 },
    comments: [],
    tags: ["kill-switch", "safety", "emergency-controls", "standards"],
    version: 1
  },
  {
    id: "idea-033",
    title: "Algorithmic Constitutionalism",
    description: "The development of formal AI constitutions for states or organizations, defining binding principles, rights, duties, and limits for algorithmic systems. Serves as a legal and normative foundation for AI governance.",
    category: "Frontier / Radical",
    authorId: "u3",
    authorName: "Elena Rodriguez",
    timestamp: new Date("2026-02-04T16:15:00Z").getTime(),
    status: "Proposed",
    impactScore: 90,
    feasibilityScore: 62,
    revenueScore: 36,
    sovereigntyScore: 92,
    votes: { up: 22, down: 2 },
    comments: [],
    tags: ["ai-constitution", "norms", "legal-frameworks", "ethics"],
    version: 1
  },
  {
    id: "idea-032",
    title: "Digital Non-Aligned Movement",
    description: "A coalition of mid-sized and emerging countries coordinating on AI governance, infrastructure standards, and procurement to reduce dependency on dominant tech powers and increase collective geopolitical leverage.",
    category: "Frontier / Radical",
    authorId: "u2",
    authorName: "James Wilson",
    timestamp: new Date("2026-02-04T16:08:00Z").getTime(),
    status: "Proposed",
    impactScore: 94,
    feasibilityScore: 56,
    revenueScore: 29,
    sovereigntyScore: 97,
    votes: { up: 31, down: 3 },
    comments: [],
    tags: ["geopolitics", "coalitions", "non-alignment", "digital-sovereignty"],
    version: 1
  },
  {
    id: "idea-031",
    title: "Public Option AI",
    description: "State-backed, openly governed, and fully audited AI models offered as a public option alternative to commercial systems. Designed to provide baseline AI capabilities with strong transparency, safety, and public-interest alignment.",
    category: "Frontier / Radical",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T16:00:00Z").getTime(),
    status: "Proposed",
    impactScore: 96,
    feasibilityScore: 59,
    revenueScore: 38,
    sovereigntyScore: 99,
    votes: { up: 56, down: 12 },
    comments: [],
    tags: ["public-option", "state-ai", "open-models", "competition"],
    version: 1
  },
  {
    id: "idea-053",
    title: "Systems View of AI (Beyond 'Just Tech')",
    description: "Frame AI as an integrated system involving capital, governance, security, leadership, and infrastructure rather than a standalone technical artifact.",
    category: "Narrative & Influence",
    authorId: "u4",
    authorName: "Marcus Thorne",
    timestamp: new Date("2026-02-04T18:25:00Z").getTime(),
    status: "Proposed",
    impactScore: 94,
    feasibilityScore: 81,
    revenueScore: 64,
    sovereigntyScore: 88,
    votes: { up: 12, down: 0 },
    comments: [],
    tags: ["systems-thinking", "ai-strategy", "holistic-view"],
    version: 1
  },
  {
    id: "idea-052",
    title: "Governance-as-Foresight Philosophy",
    description: "Position governance as anticipatory leadership and strategic foresight rather than compliance or box-ticking, shaping long-term resilience and legitimacy.",
    category: "Narrative & Influence",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T18:20:00Z").getTime(),
    status: "Proposed",
    impactScore: 96,
    feasibilityScore: 70,
    revenueScore: 61,
    sovereigntyScore: 90,
    votes: { up: 24, down: 2 },
    comments: [],
    tags: ["governance-philosophy", "foresight", "leadership"],
    version: 1
  },
  {
    id: "idea-051",
    title: "Strategic Partnerships and Co-Authorship",
    description: "Build legitimacy and influence through co-authored reports, alliances, and partnerships with credible institutions, firms, and public bodies.",
    category: "Narrative & Influence",
    authorId: "u3",
    authorName: "Elena Rodriguez",
    timestamp: new Date("2026-02-04T18:15:00Z").getTime(),
    status: "Proposed",
    impactScore: 85,
    feasibilityScore: 91,
    revenueScore: 59,
    sovereigntyScore: 78,
    votes: { up: 8, down: 1 },
    comments: [],
    tags: ["partnerships", "co-authorship", "legitimacy"],
    version: 1
  },
  {
    id: "idea-050",
    title: "Education for Platform Independence",
    description: "Reduce dependency on dominant cloud platforms by investing in education and training that builds skills in alternative infrastructures and sovereign technology stacks.",
    category: "Talent & Education",
    authorId: "u2",
    authorName: "James Wilson",
    timestamp: new Date("2026-02-04T18:10:00Z").getTime(),
    status: "Proposed",
    impactScore: 83,
    feasibilityScore: 69,
    revenueScore: 58,
    sovereigntyScore: 87,
    votes: { up: 15, down: 0 },
    comments: [],
    tags: ["education", "platform-independence", "skills"],
    version: 1
  },
  {
    id: "idea-049",
    title: "Revenue-Led Advisory and Platform Model",
    description: "Build a sustainable organization through a combination of advisory services, software platforms, and ecosystems rather than relying on venture capital dependency.",
    category: "Capital & Risk",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T18:05:00Z").getTime(),
    status: "Proposed",
    impactScore: 96,
    feasibilityScore: 87,
    revenueScore: 97,
    sovereigntyScore: 81,
    votes: { up: 32, down: 1 },
    comments: [],
    tags: ["business-model", "advisory", "platform-strategy"],
    version: 1
  },
  {
    id: "idea-048",
    title: "Staged Go-To-Market Strategy (Private → Proof → Policy)",
    description: "Adopt a phased go-to-market approach: private sector deployment, proof of value, then policy engagement and scaling through public institutions.",
    category: "Market Design",
    authorId: "u3",
    authorName: "Elena Rodriguez",
    timestamp: new Date("2026-02-04T18:00:00Z").getTime(),
    status: "Proposed",
    impactScore: 94,
    feasibilityScore: 93,
    revenueScore: 86,
    sovereigntyScore: 76,
    votes: { up: 19, down: 0 },
    comments: [],
    tags: ["go-to-market", "staged-strategy", "scaling"],
    version: 1
  },
  {
    id: "idea-047",
    title: "Business-First Policy Engagement",
    description: "Prioritize building commercial traction, revenue, and proof points before engaging deeply with government or policy processes, increasing credibility and leverage.",
    category: "Market Design",
    authorId: "u2",
    authorName: "James Wilson",
    timestamp: new Date("2026-02-04T17:55:00Z").getTime(),
    status: "Proposed",
    impactScore: 95,
    feasibilityScore: 94,
    revenueScore: 93,
    sovereigntyScore: 72,
    votes: { up: 41, down: 2 },
    comments: [],
    tags: ["go-to-market", "policy-engagement", "proof-first"],
    version: 1
  },
  {
    id: "idea-046",
    title: "Sovereignty-Aligned Foreign Capital",
    description: "Accept foreign investment into strategic AI sectors only under governance, control, and oversight structures aligned with national sovereignty objectives.",
    category: "Capital & Risk",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T17:50:00Z").getTime(),
    status: "Proposed",
    impactScore: 89,
    feasibilityScore: 67,
    revenueScore: 74,
    sovereigntyScore: 90,
    votes: { up: 28, down: 4 },
    comments: [],
    tags: ["foreign-investment", "sovereignty", "governance-controls"],
    version: 1
  },
  {
    id: "idea-045",
    title: "Hardware and Robotics Bottleneck Awareness",
    description: "Highlight and plan for hardware, robotics, and physical system constraints as key bottlenecks shaping AI progress, deployment, and geopolitical leverage.",
    category: "Sovereign Infrastructure",
    authorId: "u3",
    authorName: "Elena Rodriguez",
    timestamp: new Date("2026-02-04T17:45:00Z").getTime(),
    status: "Proposed",
    impactScore: 80,
    feasibilityScore: 56,
    revenueScore: 68,
    sovereigntyScore: 85,
    votes: { up: 14, down: 1 },
    comments: [],
    tags: ["hardware", "robotics", "compute-constraints"],
    version: 1
  },
  {
    id: "idea-044",
    title: "AI Bubble and Financial Risk Awareness",
    description: "Prepare institutions and investors for potential AI market corrections, liability exposure, and systemic financial risk through analysis, stress testing, and scenario planning.",
    category: "Capital & Risk",
    authorId: "u2",
    authorName: "James Wilson",
    timestamp: new Date("2026-02-04T17:40:00Z").getTime(),
    status: "Proposed",
    impactScore: 81,
    feasibilityScore: 78,
    revenueScore: 56,
    sovereigntyScore: 77,
    votes: { up: 55, down: 12 },
    comments: [],
    tags: ["financial-risk", "ai-bubble", "scenario-planning"],
    version: 1
  },
  {
    id: "idea-043",
    title: "Appropriate Task–System Matching for AI",
    description: "Promote disciplined matching of AI system types to specific tasks instead of defaulting to large language models, improving safety, efficiency, and explainability.",
    category: "Governance & Standards",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T17:35:00Z").getTime(),
    status: "Proposed",
    impactScore: 86,
    feasibilityScore: 90,
    revenueScore: 62,
    sovereigntyScore: 79,
    votes: { up: 21, down: 0 },
    comments: [],
    tags: ["task-matching", "system-design", "risk-reduction"],
    version: 1
  },
  {
    id: "idea-042",
    title: "AI for Compliance and ESG (Human-in-the-Loop)",
    description: "Deploy AI systems to assist regulatory, compliance, and ESG functions while keeping humans in the loop for judgment, escalation, and accountability.",
    category: "Market Design",
    authorId: "u4",
    authorName: "Marcus Thorne",
    timestamp: new Date("2026-02-04T17:30:00Z").getTime(),
    status: "Proposed",
    impactScore: 88,
    feasibilityScore: 92,
    revenueScore: 85,
    sovereigntyScore: 75,
    votes: { up: 36, down: 3 },
    comments: [],
    tags: ["compliance-ai", "esg", "human-in-the-loop"],
    version: 1
  },
  {
    id: "idea-041",
    title: "Focus on SLMs, Explainable and Hybrid AI",
    description: "Prioritize small language models, explainable systems, and hybrid AI approaches rather than competing in large-scale LLM arms races dominated by hyperscalers.",
    category: "Market Design",
    authorId: "u3",
    authorName: "Elena Rodriguez",
    timestamp: new Date("2026-02-04T17:25:00Z").getTime(),
    status: "Proposed",
    impactScore: 94,
    feasibilityScore: 84,
    revenueScore: 80,
    sovereigntyScore: 89,
    votes: { up: 49, down: 1 },
    comments: [],
    tags: ["slms", "explainable-ai", "hybrid-ai", "strategic-focus"],
    version: 1
  },
  {
    id: "idea-040",
    title: "UK Scale-Up and Capital Reform",
    description: "Reform capital markets and ownership rules to retain intellectual property, restrict strategic foreign acquisition, and fund domestic AI scale-up.",
    category: "Capital & Risk",
    authorId: "u2",
    authorName: "James Wilson",
    timestamp: new Date("2026-02-04T17:20:00Z").getTime(),
    status: "Proposed",
    impactScore: 93,
    feasibilityScore: 54,
    revenueScore: 70,
    sovereigntyScore: 94,
    votes: { up: 68, down: 5 },
    comments: [],
    tags: ["scale-up", "capital-reform", "ip-retention"],
    version: 1
  },
  {
    id: "idea-039",
    title: "Tech Sovereignty and Stack Control",
    description: "Ensure national control over critical AI infrastructure including cloud, data, compute, and core systems, reducing strategic dependency on external providers.",
    category: "Sovereign Infrastructure",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T17:15:00Z").getTime(),
    status: "Proposed",
    impactScore: 97,
    feasibilityScore: 55,
    revenueScore: 65,
    sovereigntyScore: 99,
    votes: { up: 112, down: 4 },
    comments: [],
    tags: ["tech-sovereignty", "stack-control", "strategic-infrastructure"],
    version: 1
  },
  {
    id: "idea-038",
    title: "Board-Level AI Accountability",
    description: "Require boards to understand, oversee, and formally document AI usage, risks, and governance arrangements, embedding accountability at the highest organizational level.",
    category: "Governance & Standards",
    authorId: "u3",
    authorName: "Elena Rodriguez",
    timestamp: new Date("2026-02-04T17:10:00Z").getTime(),
    status: "Proposed",
    impactScore: 92,
    feasibilityScore: 80,
    revenueScore: 71,
    sovereigntyScore: 83,
    votes: { up: 29, down: 2 },
    comments: [],
    tags: ["board-accountability", "corporate-oversight", "ai-risk"],
    version: 1
  },
  {
    id: "idea-037",
    title: "Beyond Compliance Corporate AI Governance",
    description: "Encourage firms to internalize AI governance best practices and exceed minimum regulatory requirements, positioning governance as a source of resilience and competitive advantage.",
    category: "Governance & Standards",
    authorId: "u2",
    authorName: "James Wilson",
    timestamp: new Date("2026-02-04T17:05:00Z").getTime(),
    status: "Proposed",
    impactScore: 89,
    feasibilityScore: 72,
    revenueScore: 82,
    sovereigntyScore: 78,
    votes: { up: 18, down: 1 },
    comments: [],
    tags: ["beyond-compliance", "corporate-governance", "best-practice"],
    version: 1
  },
  {
    id: "idea-036",
    title: "Proactive, Coherent AI Governance",
    description: "Shift AI governance from reactive, crisis-driven regulation to anticipatory, system-wide oversight. Emphasizes foresight, continuous supervision, and institutional coherence rather than post-hoc interventions.",
    category: "Governance & Standards",
    authorId: "u1",
    authorName: "Dr. Sarah Chen",
    timestamp: new Date("2026-02-04T17:00:00Z").getTime(),
    status: "Proposed",
    impactScore: 95,
    feasibilityScore: 58,
    revenueScore: 40,
    sovereigntyScore: 92,
    votes: { up: 44, down: 3 },
    comments: [],
    tags: ["anticipatory-governance", "systemic-oversight", "institutional-reform"],
    version: 1
  }
];
